<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>PipelogiqSDK</PackageId>
    <Version>0.1.0-preview.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hashids.net" Version="1.7.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Link="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
