<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pipelogiq.Sdk/PipelogiqSDK.csproj" />
    <ProjectReference Include="../../src/Pipelogiq.Sdk.Redis/Pipelogiq.Sdk.Redis.csproj" />
    <ProjectReference Include="../../src/Pipelogiq.Sdk.Postgres/Pipelogiq.Sdk.Postgres.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.9.0-beta.2" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
  </ItemGroup>
</Project>
